# Generated by Django 5.0.2 on 2024-03-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='conteudos_vistos',
            field=models.ManyToManyField(to='conteudo.conteudo_db'),
        ),
    ]
