# Generated by Django 5.0.2 on 2024-03-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filme',
            new_name='Conteudo_db',
        ),
    ]
