# Generated by Django 5.0.2 on 2024-03-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0002_rename_filme_conteudo_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo_db',
            name='categoria',
            field=models.CharField(choices=[('analises', 'Análises'), ('PROGRAMACAO', 'Programação'), ('APRESENTACAO', 'Apresentação'), ('OUTROS', 'Outros')], max_length=15),
        ),
    ]
