# Generated by Django 5.0.2 on 2024-03-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0003_alter_conteudo_db_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo_db',
            name='thumb',
            field=models.ImageField(upload_to='thumb_conteudo/'),
        ),
    ]
