# Generated by Django 5.0.2 on 2024-03-11 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0004_alter_conteudo_db_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('Conteudo_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='conteudo.conteudo_db')),
            ],
        ),
    ]
